Remove dynamic PGO option and make it default
space-wizards/SS14.Launcher pull request #130
Opened 2024-01-05 16:51 UTC by VasilisThePikachu

As far as I know, no one has experienced an issue with it. May as well remove some clutter. And make sure its on by default

2024-01-05 17:11 UTC, deathride58 commented
The setting is somewhat useful; dynamic PGO does add a bit of startup time to the client, due to how large the assembly is. Though making it default would probably be a good idea.

2024-01-05 17:21 UTC, VasilisThePikachu commented
> The setting is somewhat useful; dynamic PGO does add a bit of startup time to the client, due to how large the assembly is. Though making it default would probably be a good idea.

I would take client performance over a little bit extra startup time

2024-01-05 17:44 UTC, deathride58 commented
The extra startup time is not insignificant on lower-end hardware

2024-01-05 18:10 UTC, VasilisThePikachu commented
How much longer is it? And how low end are we talking?

2024-01-06 18:24 UTC, PJB3005 commented
> The extra startup time is not insignificant on lower-end hardware

Do you have numbers on this?

2024-01-06 18:37 UTC, deathride58 commented
We do not, admittedly! Plus it's been quite a while since we last poked at it ourself (and coincidentally it's been quite a while since we had a computer where it actually mattered). It's something that should probably be benchmarked proper.

2024-01-06 20:03 UTC, PJB3005 commented
We could turn the checkmark into something that disables Full PGO instead, and clearly mark it as such.

2024-01-06 22:02 UTC, VasilisThePikachu commented
So this is on decently good hardware. But having the option turned on or off does not impact startup time at all.

2024-01-07 17:22 UTC, VasilisThePikachu commented
Some more findings: on a MacBook air m1

With pgo enabled: 30 second to get from launcher to game
With pgo off: 25 seconds

2024-01-09 22:35 UTC, PJB3005 requested changes

2024-01-09 22:35 UTC, PJB3005 commented on SS14.Launcher/Models/Connector.cs
> +        EnvVar("DOTNET_TC_QuickJitForLoops", "1");
`DOTNET_TC_QuickJitForLoops` is default since .NET 7, remove the set for it.

2024-01-17 00:21 UTC, merged